### ISSUE TITLE
Frage zu Grass-ICS

### ISSUE THREAD

**Issue by DanielRieken** [DanielRieken/Grass-ICS#1]
Hallo @Bombenleger
kann ich dich mal was zu Grass-ICS (https://github.com/Bombenleger/Grass-ICS) fragen?

Ich habs bisher immer die originale com.android.wallpaper-APK verwendet. Bis LineageOS 14.1 (Android 7.1) hat die auch prima funktioniert.
Unter LineageOS 17.1 (Android 10) lässt sich die APK nun leider nicht mehr installieren.
Habe dann dein Grass-ICS gefunden und wollte ausprobieren, ob das unter Android 10 läuft. Doch leider bekomme ich das im Android-Studio nicht kompiliert.
Deswegen wollte ich mal fragen: weißt du, ob das unter Android 10 läuft?

Hätte so gerne das Grass Livewallpaper wieder :) Wäre cool, wenn du kurz antwortest :-)

**Comment by Bombenleger** [comment]
Hallo @DanielRieken,

ich habe es auch nicht geschafft diese Version auf neueren Android-Versionen zu kompilieren. Denke das liegt an der verwendeten Grafik-Library, die es nur bei alten Versionen gibt.

Ich benutze mittlerweile den hier, da hat sich wohl jemand die Mühe gemacht diese Lib auszutauschen: https://play.google.com/store/apps/details?id=h.bigga.bigga.lwp.grass

**Comment by DanielRieken** [comment]
@Bombenleger 
super, vielen Dank!
